# Generated by Django 4.0 on 2021-12-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='creator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='opponent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
