# Generated by Django 4.0 on 2021-12-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=100)),
                ('opponent', models.CharField(max_length=100)),
                ('room_code', models.CharField(max_length=30)),
            ],
        ),
    ]
